{
 "title": "Linky @ FIXME Adress",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Puissance Instantanée",
   "type": "gauge",
   "description": "Puissance consommée instantanée (approximative, facteur de puissance de 1)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"PAPP\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "timeseries",
   "description": "Puissance apparente (PAPP) indiquée par le Linky",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"PAPP\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance apparente\" }))"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"IINST\" and r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "timeseries",
   "description": "Valeur IINST de la Téléinfo Linky : intensité instantanée (en ampères)",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"IINST\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Intensité instantanée\" }))"
    },
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"ISOUSC\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Intensité souscrite\" }))"
    }
   ]
  },
  {
   "title": "Index Linky",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"BASE\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000}))\n"
    }
   ]
  },
  {
   "title": "Energie consommée sur la période",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"BASE\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Mois en cours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"BASE\" and r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance consommée\" }))\n  "
    }
   ]
  },
  {
   "title": "12 derniers mois",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"BASE\" and r._field == \"value\")\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance consommée\" }))"
    }
   ]
  },
  {
   "title": "Coût énergie sur la période",
   "type": "stat",
   "description": "Coût au Tarif Bleu Option Base. \nPrix unitaire du kWh0,2062 €",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"BASE\" and r._field == \"value\")\n  |> spread()\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 * 0.2264}))\n\n  "
    }
   ]
  }
 ]
}