{
 "title": "Linky @ Saone",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Periode En Cours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"PTEC\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: strings.trimSuffix(v: r._value, suffix: \"..\")}))"
    }
   ]
  },
  {
   "title": "Index Linky HP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHP\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value / 1000}))"
    }
   ]
  },
  {
   "title": "Index Linky HC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value / 1000}))\n"
    }
   ]
  },
  {
   "title": "Energie consommée en HP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHP\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Energie consommée en HC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Energie consommée totale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" or r._measurement == \"HCHP\" and r._field == \"value\")\n  |> spread()\n  |> group(columns: [\"location\"], mode:\"by\")  \n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Répartition HP / HC sur la période",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" or r._measurement == \"HCHP\" and r._field == \"value\")\n  |> spread()\n  |> group(columns: [\"_measurement\"], mode:\"by\")  \n  |> rename(columns: {_value: \"\"})\n  |> map(fn: (r) => ({r with _measurement: strings.replace(v: r._measurement, t: \"HCHC\", u: \"Heures Creuses\", i: 1)}))\n  |> map(fn: (r) => ({r with _measurement: strings.replace(v: r._measurement, t: \"HCHP\", u: \"Heures Pleines\", i: 1)}))\n\n"
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "timeseries",
   "description": "Puissance apparente (PAPP) indiquée par le Linky",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"PAPP\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance apparente\" }))"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "timeseries",
   "description": "Valeur IINST de la Téléinfo Linky : intensité instantanée (en ampères)",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"IINST\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Intensité instantanée\" }))"
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"ISOUSC\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Intensité souscrite\" }))"
    }
   ]
  },
  {
   "title": "Puissance Instantanée",
   "type": "gauge",
   "description": "Puissance consommée instantanée (approximative, facteur de puissance de 1)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"PAPP\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"IINST\" and r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Mois en cours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"HCHP\" and r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HP\" }))\n  "
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" and r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HC\" }))\n  "
    }
   ]
  },
  {
   "title": "12 derniers mois",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"HCHP\" and r._field == \"value\")\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HP\" }))"
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" and r._field == \"value\")\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HC\" }))"
    }
   ]
  },
  {
   "title": "Coût énergie sur la période",
   "type": "stat",
   "description": "Coût au Tarif Bleu Option Base. \nPrix unitaire du kWh0,2062 €",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"HCHC\" or r._measurement == \"HCHP\" and r._field == \"value\")\n  |> spread()\n  |> toFloat()\n  |> group(columns: [\"location\"], mode:\"by\")  \n  |> map(fn: (r) => ({r with _value: \n            if (r._measurement == \"HCHP\") then (r._value / 1000.0 * 0.178754)\n            else (r._value / 1000.0 * 0.141854)\n        }))\n  |> sum(column: \"_value\")"
    }
   ]
  }
 ]
}