{
 "title": "Linky @ Saone",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Periode En Cours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"LTARF\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: strings.trimSuffix(v: r._value, suffix: \"..\")}))"
    }
   ]
  },
  {
   "title": "Puissance Instantanée",
   "type": "gauge",
   "description": "Puissance consommée instantanée (approximative, facteur de puissance de 1)",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"SINSTS\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"IRMS1\" and r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Puissance Injectée Instantanée",
   "type": "stat",
   "description": "Puissance consommée instantanée (approximative, facteur de puissance de 1)",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> last()\n  |> filter(fn: (r) => r._measurement == \"SINSTI\" and r._field == \"value\")\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Répartition HP / HC sur la période",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" or r._measurement == \"EASF02\" and r._field == \"value\")\n  |> spread()\n  |> group(columns: [\"_measurement\"], mode:\"by\")  \n  |> rename(columns: {_value: \"\"})\n  |> map(fn: (r) => ({r with _measurement: strings.replace(v: r._measurement, t: \"EASF01\", u: \"Heures Creuses\", i: 1)}))\n  |> map(fn: (r) => ({r with _measurement: strings.replace(v: r._measurement, t: \"EASF02\", u: \"Heures Pleines\", i: 1)}))\n\n"
    }
   ]
  },
  {
   "title": "Tension efficace phase 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"URMS1\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value}))"
    }
   ]
  },
  {
   "title": "Index energie soutirée totale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EAST\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value}))"
    }
   ]
  },
  {
   "title": "Index Energie Soutirée HP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF02\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value}))"
    }
   ]
  },
  {
   "title": "Index Energie Soutirée HC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Index Injection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EAIT\" and r._field == \"value\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Energie consommée totale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EAST\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Energie consommée en HP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF02\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Energie consommée en HC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Energie injectée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EAIT\" and r._field == \"value\")\n  |> spread()\n  \n  "
    }
   ]
  },
  {
   "title": "Coût énergie sur la période",
   "type": "stat",
   "description": "Coût au Tarif Bleu Option Base. \nPrix unitaire du kWh0,2062 €",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" or r._measurement == \"EASF02\" and r._field == \"value\")\n  |> spread()\n  |> toFloat()\n  |> group(columns: [\"location\"], mode:\"by\")  \n  |> map(fn: (r) => ({r with _value: \n            if (r._measurement == \"EASF02\") then (r._value / 1000.0 * 0.178754)\n            else (r._value / 1000.0 * 0.141854)\n        }))\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Puissance apparente",
   "type": "timeseries",
   "description": "Puissance apparente (PAPP) indiquée par le Linky",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SINSTS\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance apparente soutirée\" }))"
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SINSTI\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance apparente injectée\" }))"
    }
   ]
  },
  {
   "title": "Intensité instantanée",
   "type": "timeseries",
   "description": "Valeur IINST de la Téléinfo Linky : intensité instantanée (en ampères)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"IRMS1\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Intensité instantanée\" }))"
    }
   ]
  },
  {
   "title": "Mois en cours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"EASF02\" and r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HP\" }))\n  "
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" and r._field == \"value\")\n  |> aggregateWindow(every: 1d, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HC\" }))\n  "
    }
   ]
  },
  {
   "title": "12 derniers mois",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"EASF02\" and r._field == \"value\")\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HP\" }))"
    },
    {
     "query": "from(bucket: \"linky-saone\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r._measurement == \"EASF01\" and r._field == \"value\")\n  |> aggregateWindow(every: 1mo, fn: spread, createEmpty: true)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"Puissance HC\" }))"
    }
   ]
  }
 ]
}